name: build and deploy to ghcr

on:
  push:
    branches:
      - main 
  

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login to container registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build project
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ghcr.io/${{ vars.REPOSITORY }}:latest
      #       ghcr.io/${{ vars.REPOSITORY }}:${{ github.run_number }}
            
         # Step : Build the Docker image
      - name: Build Docker image
        run: |
         docker build -t ghcr.io/${{ vars.REPOSITORY }}/some_static_site:latest .
   
         # Step 4: Slim the Docker image using Kitabisa Action
      - name: Slim Docker image
        uses: kitabisa/docker-slim-action@v1
        env:
         DSLIM_HTTP_PROBE: "false"  # Disables HTTP probing during slimming
        with:
         target: ghcr.io/${{ vars.REPOSITORY }}/some_static_site:latest  # Target image to slim
         tag: latest  # Suffix for the slimmed image tag

    # Step 5: Push the slimmed image to GitHub Container Registry.
      - name: Push slimmed Docker image
        run: |
         docker push ghcr.io/${{ vars.REPOSITORY }}/some_static_site:latest  
